# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  DistFolder: dist

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.1.0'
  displayName: 'Install Node.js'

- script: |
    npm install -g ember-cli@3.1.4
  displayName: 'ember cli install'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm install -g json-server
  displayName: 'json-server install'

- script: |
    ember build
  displayName: 'ember build'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/$(DistFolder)'